force-app/main/default/objects/Related_Records_Highlight_Panel_Setting__mdt/Related_Records_Highlight_Panel_Setting__mdt.object-meta.xml
<CustomObject>
    <description>Settings for how to render the custom Related Records Highlights panel</description>
    <label>Related Records Highlight Panel Setting</label>
    <pluralLabel>Related Record Highlight Panel Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Related_Records_Highlight_Panel_Setting__mdt/fields/Component_Id__c.field-meta.xml
<CustomField>
    <fullName>Component_Id__c</fullName>
    <description>Identifies which instance of a Component that this highlight item should be displayed in. The Id here should be the same as entered on the Component in the Lightning Record Page.</description>
    <inlineHelpText>Identifies which instance of a Component that this highlight item should be displayed in. The Id here should be the same as entered on the Component in the Lightning Record Page.</inlineHelpText>
    <label>Component Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Related_Records_Highlight_Panel_Setting__mdt/fields/Icon__c.field-meta.xml
<CustomField>
    <fullName>Icon__c</fullName>
    <description>The icon to use - Should use the SLDS icons documented here:
https://www.lightningdesignsystem.com/icons/</description>
    <label>Icon</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Related_Records_Highlight_Panel_Setting__mdt/fields/Item_Name__c.field-meta.xml
<CustomField>
    <fullName>Item_Name__c</fullName>
    <description>The text that will be shown as the header of the highlight item</description>
    <label>Item Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Related_Records_Highlight_Panel_Setting__mdt/fields/Items_Query__c.field-meta.xml
<CustomField>
    <fullName>Items_Query__c</fullName>
    <description>The query that should be used to fetch the items to display

The query should use the :recordId parameter to indicate the &quot;Parent record&quot; id. Ex:

To get all cases related to the account:
SELECT Subject FROM Case WHERE AccountId = :recordId</description>
    <inlineHelpText>SOQL query for fetching hightlight items. The id of the parent record is passed as :recordId</inlineHelpText>
    <label>Items Query</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Related_Records_Highlight_Panel_Setting__mdt/fields/SObject_Name__c.field-meta.xml
<CustomField>
    <fullName>SObject_Name__c</fullName>
    <description>The name of the SObject to render</description>
    <label>SObject Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Related_Records_Highlight_Panel_Setting__mdt/fields/Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order__c</fullName>
    <description>The order that columns should be shown. Goes from 0 - 9</description>
    <inlineHelpText>0-9</inlineHelpText>
    <label>Sort Order</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Related_Records_Highlight_Panel_Setting__mdt/fields/Table_Columns__c.field-meta.xml
<CustomField>
    <fullName>Table_Columns__c</fullName>
    <description>Columns to show in records table</description>
    <inlineHelpText>In Display Order. Separated by &quot;,&quot;. 
Example:
Name,Title,Status,NumberOfCases__c

Note: First Column will be the record link.</inlineHelpText>
    <label>Table Columns</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RelatedRecordsHighlightsControllerTests.cls
@IsTest
public with sharing class RelatedRecordsHighlightsControllerTests {

    @isTest
    private static void three_highlights_should_be_returned_when_three_have_been_configured() {
        // Test data setup
        List<Contact> fakeContacts = new List<Contact>();
        for(Integer i = 0; i < 20; i++){
            Contact c = new Contact(
                FirstName = 'test',
                LastName = 'test'+i
            );
            fakeContacts.add(c);
        } 
        
        List<Case> fakeCases = new List<Case>();
        for(Integer i = 0; i < 20; i++){
            Case c = new Case(
                Subject = 'test ' + i,
                description = 'test'
            );
            fakeCases.add(c);
        } 
        FakeSelector selector = new FakeSelector(fakeCases,fakeContacts);

        Map<String, Related_Records_Highlight_Panel_Setting__mdt> settings = generateSettingsMap();

        RelatedRecordsHighlightsController.settings = settings;
        RelatedRecordsHighlightsController.recordsSelector = selector;

        // Actual test
        Test.startTest();
        List<RelatedRecordsHighlightsController.HighlightItemWrapper> wrappers = RelatedRecordsHighlightsController.getHighlightItems('SomeId','AccountPage');
        Test.stopTest();
    
        // Asserts
        Assert.isNotNull(wrappers);
        Assert.areEqual(3,wrappers.size());
    }
    @isTest
    private static void should_only_return_wrappers_for_the_provided_componentId() {
        // Test data setup
        List<Contact> fakeContacts = new List<Contact>();
        for(Integer i = 0; i < 5; i++){
            Contact c = new Contact(
                FirstName = 'test',
                LastName = 'test'+i
            );
            fakeContacts.add(c);
        } 
        
        List<Case> fakeCases = new List<Case>();
        for(Integer i = 0; i < 5; i++){
            Case c = new Case(
                Subject = 'test ' + i,
                description = 'test'
            );
            fakeCases.add(c);
        } 
        FakeSelector selector = new FakeSelector(fakeCases,fakeContacts);

        Map<String, Related_Records_Highlight_Panel_Setting__mdt> settings = generateSettingsMap();
        settings.get('Cases').Component_Id__c = '';

        RelatedRecordsHighlightsController.settings = settings;
        RelatedRecordsHighlightsController.recordsSelector = selector;

        // Actual test
        Test.startTest();
        List<RelatedRecordsHighlightsController.HighlightItemWrapper> wrappers = RelatedRecordsHighlightsController.getHighlightItems('SomeId','AccountPage');
        Test.stopTest();
    
        // Asserts
        Assert.isNotNull(wrappers);
        Assert.areEqual(2,wrappers.size());
    }
    @isTest
    private static void failed_query_should_return_wrapper_with_error() {
        // Test data setup
        List<Contact> fakeContacts = new List<Contact>();
        for(Integer i = 0; i < 5; i++){
            Contact c = new Contact(
                FirstName = 'test',
                LastName = 'test'+i
            );
            fakeContacts.add(c);
        } 
        
        List<Case> fakeCases = new List<Case>();
        for(Integer i = 0; i < 5; i++){
            Case c = new Case(
                Subject = 'test ' + i,
                description = 'test'
            );
            fakeCases.add(c);
        } 
        FakeSelector selector = new FakeSelector(fakeCases,fakeContacts);

        Map<String, Related_Records_Highlight_Panel_Setting__mdt> settings = generateSettingsMap();
        
        RelatedRecordsHighlightsController.settings = new Map<String,Related_Records_Highlight_Panel_Setting__mdt>{'Cases' => settings.get('Cases')};
        RelatedRecordsHighlightsController.recordsSelector = selector;
        RelatedRecordsHighlightsController.throwQueryException = true;

        // Actual test
        Test.startTest();
        List<RelatedRecordsHighlightsController.HighlightItemWrapper> wrappers = RelatedRecordsHighlightsController.getHighlightItems('SomeId','AccountPage');
        Test.stopTest();
    
        // Asserts
        Assert.isTrue(wrappers[0].errors.size() > 0,'The wrapper should have errors.');
        Assert.isTrue(wrappers[0].numOfItems == 0,'The wrapper record counter should be 0');
        Assert.isNull(wrappers[0].records,'There should be no records in this wrapper.');
    }
    @IsTest
    private static void generic_uncaught_exception_should_be_rethrown_as_aurahandeledException(){
        RelatedRecordsHighlightsController.throwException = true;

        Exception caughtException;
        try {
            List<RelatedRecordsHighlightsController.HighlightItemWrapper> wrappers = RelatedRecordsHighlightsController.getHighlightItems('SomeId','AccountPage');
        }catch(Exception ex){
            caughtException = ex;
        }

        Assert.isNotNull(caughtException, 'An exception should have been caught.');
        Assert.isInstanceOfType(caughtException, AuraHandledException.class,'');
    }

    @IsTest
    private static void returned_wrappers_should_be_sorted_in_ascending_order(){
        // Test data setup
        List<Contact> fakeContacts = new List<Contact>();
        for(Integer i = 0; i < 5; i++){
            Contact c = new Contact(
                FirstName = 'test',
                LastName = 'test'+i
            );
            fakeContacts.add(c);
        } 
        
        List<Case> fakeCases = new List<Case>();
        for(Integer i = 0; i < 5; i++){
            Case c = new Case(
                Subject = 'test ' + i,
                description = 'test'
            );
            fakeCases.add(c);
        } 
        FakeSelector selector = new FakeSelector(fakeCases,fakeContacts);

        Map<String, Related_Records_Highlight_Panel_Setting__mdt> settings = generateSettingsMap();

        RelatedRecordsHighlightsController.settings = settings;
        RelatedRecordsHighlightsController.recordsSelector = selector;

        // Actual test
        Test.startTest();
        List<RelatedRecordsHighlightsController.HighlightItemWrapper> wrappers = RelatedRecordsHighlightsController.getHighlightItems('SomeId','AccountPage');
        Test.stopTest();

        // Asserts
        Assert.isTrue(wrappers[0].sortOrder < wrappers[1].sortOrder, 'The wrappers are not in the expected order');
        Assert.isTrue(wrappers[1].sortOrder < wrappers[2].sortOrder, 'The wrappers are not in the expected order');
        
    }

    private static Map<String,Related_Records_Highlight_Panel_Setting__mdt> generateSettingsMap(){

        Related_Records_Highlight_Panel_Setting__mdt casesSetting = new Related_Records_Highlight_Panel_Setting__mdt(
            Label = 'Cases',
            DeveloperName = 'Cases',
            SObject_Name__c = 'Case',
            Item_Name__c = 'Cases',
            Items_Query__c = 'Select Id,Subject,Type FROM Case WHERE Id = :recordId',
            Icon__c = 'standard:case',
            Sort_Order__c = 2,
            Table_Columns__c = 'Subject,Type',
            Component_Id__c = 'AccountPage'
        );

        Related_Records_Highlight_Panel_Setting__mdt contactsSetting = new Related_Records_Highlight_Panel_Setting__mdt(
            Label = 'Contacts',
            DeveloperName = 'Contacts',
            SObject_Name__c = 'Contact',
            Item_Name__c = 'Contacts',
            Items_Query__c = 'Select Id,Name,Title FROM Contact WHERE AccountId = :recordId',
            Icon__c = 'standard:contact',
            Sort_Order__c = 0,
            Table_Columns__c = 'Name,Title',
            Component_Id__c = 'AccountPage'
        );

        Related_Records_Highlight_Panel_Setting__mdt unhappyContactsSetting = new Related_Records_Highlight_Panel_Setting__mdt(
            Label = 'Unhappy Contacts',
            DeveloperName = 'Unhappy_Contacts',
            SObject_Name__c = 'Contact',
            Item_Name__c = 'Contacts',
            Items_Query__c = 'Select Id,Name,Title FROM Contact WHERE AccountId = :recordId',
            Icon__c = 'standard:contact',
            Sort_Order__c = 1,
            Table_Columns__c = 'Name,Title',
            Component_Id__c = 'AccountPage'
        );

        Map<String,Related_Records_Highlight_Panel_Setting__mdt> settingsMap = new Map<String,Related_Records_Highlight_Panel_Setting__mdt>{
            casesSetting.DeveloperName => casesSetting,
            contactsSetting.DeveloperName => contactsSetting,
            unhappyContactsSetting.DeveloperName => unhappyContactsSetting
        };
        return settingsMap; 
    }

    /**
     * A fake selector is used so that we can test with real fake data, and make the test org-agnostic.
    */
    private inherited sharing class FakeSelector extends RelatedRecordsHighlightsController.Selector {
        private List<Contact> theContactRecords;
        private List<Case> theCaseRecords;
        public FakeSelector(List<Case> theCases, List<Contact> theContacts){
            this.theCaseRecords = theCases;
            this.theContactRecords = theContacts;
        }

        public override List<SObject> getRecordsDynamic(String query,Map<String,String> binds,AccessLevel queryMode) {

            if(query.contains('Case')){
                return this.theCaseRecords;
            }

            if(query.contains('Contact')){
                return this.theContactRecords;
            }
            return new List<SObject>();
        }
    }
}