force-app/main/default/objects/Related_Records_Highlight_Panel_Setting__mdt/Related_Records_Highlight_Panel_Setting__mdt.object-meta.xml
<CustomObject>
    <description>Settings for how to render the custom Related Records Highlights panel</description>
    <label>Related Records Highlight Panel Setting</label>
    <pluralLabel>Related Record Highlight Panel Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Related_Records_Highlight_Panel_Setting__mdt/fields/Component_Id__c.field-meta.xml
<CustomField>
    <fullName>Component_Id__c</fullName>
    <description>Identifies which instance of a Component that this highlight item should be displayed in. The Id here should be the same as entered on the Component in the Lightning Record Page.</description>
    <inlineHelpText>Identifies which instance of a Component that this highlight item should be displayed in. The Id here should be the same as entered on the Component in the Lightning Record Page.</inlineHelpText>
    <label>Component Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Related_Records_Highlight_Panel_Setting__mdt/fields/Icon__c.field-meta.xml
<CustomField>
    <fullName>Icon__c</fullName>
    <description>The icon to use - Should use the SLDS icons documented here:
https://www.lightningdesignsystem.com/icons/</description>
    <label>Icon</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Related_Records_Highlight_Panel_Setting__mdt/fields/Item_Name__c.field-meta.xml
<CustomField>
    <fullName>Item_Name__c</fullName>
    <description>The text that will be shown as the header of the highlight item</description>
    <label>Item Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Related_Records_Highlight_Panel_Setting__mdt/fields/Items_Query__c.field-meta.xml
<CustomField>
    <fullName>Items_Query__c</fullName>
    <description>The query that should be used to fetch the items to display

The query should use the :recordId parameter to indicate the &quot;Parent record&quot; id. Ex:

To get all cases related to the account:
SELECT Subject FROM Case WHERE AccountId = :recordId</description>
    <inlineHelpText>SOQL query for fetching hightlight items. The id of the parent record is passed as :recordId</inlineHelpText>
    <label>Items Query</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Related_Records_Highlight_Panel_Setting__mdt/fields/SObject_Name__c.field-meta.xml
<CustomField>
    <fullName>SObject_Name__c</fullName>
    <description>The name of the SObject to render</description>
    <label>SObject Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Related_Records_Highlight_Panel_Setting__mdt/fields/Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order__c</fullName>
    <description>The order that columns should be shown. Goes from 0 - 9</description>
    <inlineHelpText>0-9</inlineHelpText>
    <label>Sort Order</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Related_Records_Highlight_Panel_Setting__mdt/fields/Table_Columns__c.field-meta.xml
<CustomField>
    <fullName>Table_Columns__c</fullName>
    <description>Columns to show in records table</description>
    <inlineHelpText>In Display Order. Separated by &quot;,&quot;. 
Example:
Name,Title,Status,NumberOfCases__c

Note: First Column will be the record link.</inlineHelpText>
    <label>Table Columns</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RelatedRecordsHighlightsController.cls
public with sharing class RelatedRecordsHighlightsController {

    @TestVisible
    public static RelatedRecordsHighlightsController.Selector recordsSelector;
    @TestVisible
    public static Map<String, Related_Records_Highlight_Panel_Setting__mdt> settings;
    @TestVisible
    public static Boolean throwException = false;
    @TestVisible
    public static Boolean throwQueryException = false;

    @AuraEnabled
    public static List<HighlightItemWrapper> getHighlightItems(
        String recordId,
        String componentId
    ) {
        recordsSelector = new Selector();
        Map<String, List<String>> errorMap = new Map<String, List<String>>();
        try {
            if(Test.isRunningTest() && throwException){
                throw new QueryException();
            }

            List<HighlightItemWrapper> wrappers = new List<HighlightItemWrapper>();

            if(settings == null){
                settings = Related_Records_Highlight_Panel_Setting__mdt.getAll();
            }

            Integer itemIdIterator = 0;
            for (
                Related_Records_Highlight_Panel_Setting__mdt setting : settings.values()
            ) {
                List<String> componentIds = setting.Component_Id__c
                    ?.split(',') ?? new List<String>();

                if (!componentIds.contains(componentId)) {
                    continue;
                }

                Map<String, String> binds = new Map<String, String>{
                    'recordId' => recordId
                };
                String query = setting.Items_Query__c;

                String currentItemId = 'HI' + itemIdIterator;

                HighlightItemWrapper wrapper = new HighlightItemWrapper();
                wrapper.itemId = currentItemId;
                wrapper.header = setting.Item_Name__c;
                wrapper.icon = setting.Icon__c;
                wrapper.sortOrder = (Integer) setting.Sort_Order__c;
                try {
                    if(Test.isRunningTest() && throwQueryException){
                        throw new QueryException('Testing Exception');
                    }
                    List<SObject> records = recordsSelector.getRecordsDynamic(
                        query,
                        binds,
                        AccessLevel.USER_MODE
                    );

                    wrapper.records = records;
                    wrapper.numOfItems = records?.size();
                    wrapper.fields = parseForFieldLabel(
                        setting.Table_Columns__c.split(','),
                        setting.SObject_Name__c
                    );
                } catch (QueryException qe) {
                    wrapper.numOfItems = 0;
                    wrapper.records = null;
                    wrapper.errors = new List<String>{
                        formatErrorMessage(qe, setting.Item_Name__c)
                    };
                }
                wrappers.add(wrapper);
                itemIdIterator++;
            }
            wrappers.sort();
            return wrappers;
        } catch (Exception e) {
            System.debug(e.getStackTraceString());
            throw new AuraHandledException(e.getMessage());
        }
    }

    private static String formatErrorMessage(Exception ex, String itemName) {
        return String.format(
            '{0} query failed due to: "{1}"',
            new List<String>{ itemName, ex.getMessage() }
        );
    }

    private static List<Field> parseForFieldLabel(
        List<String> fieldsToParse,
        String ObjectName
    ) {
        List<Field> fieldList = new List<Field>();

        Schema.DescribeSObjectResult result = Schema.describeSObjects(
            new List<String>{ ObjectName }
        )[0];
        Map<String, Schema.SObjectField> fieldsMap = result.fields.getMap();
        for (String name : fieldsToParse) {
            Field f = new Field(
                fieldsMap?.get(name)?.getDescribe()?.getLabel(),
                name
            );
            fieldList.add(f);
        }
        return fieldList;
    }

    @TestVisible
    private virtual with sharing class Selector {
        public virtual List<SObject> getRecordsDynamic (String query,Map<String,String> binds,AccessLevel queryMode){
            return (List<SObject>) Database.queryWithBinds(
                query,
                binds,
                queryMode
            );
        }
    }

    public class HighlightItemWrapper implements Comparable {
        @AuraEnabled
        public String itemId { get; set; }
        @AuraEnabled
        public String header { get; set; }
        @AuraEnabled
        public String icon { get; set; }
        @AuraEnabled
        public Integer numOfItems { get; set; }
        @AuraEnabled
        public Integer sortOrder { get; set; }
        @AuraEnabled
        public List<Field> fields { get; set; }
        @AuraEnabled
        public List<SObject> records { get; set; }
        @AuraEnabled
        public List<String> errors { get; set; }

        public Integer compareTo(Object compareTo) {
            HighlightItemWrapper compareToWrapper = (HighlightItemWrapper) compareTo;
            if (sortOrder == compareToWrapper.sortOrder)
                return 0;
            if (sortOrder > compareToWrapper.sortOrder)
                return 1;
            return -1;
        }
    }

    public class Field {
        @AuraEnabled
        public String label;
        @AuraEnabled
        public String name;

        public Field(String label, String name) {
            this.label = label;
            this.name = name;
        }
    }
}